apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    app.kubernetes.io/name: checkpoint-native-preemption-controller
spec:
  selector:
    app.kubernetes.io/name: checkpoint-native-preemption-controller
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
