//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *CheckpointPolicy) DeepCopyInto(out *CheckpointPolicy) {
	*out = *in
	out.Interval = in.Interval
	out.FreshnessBudget = in.FreshnessBudget
	out.MaxDrainTime = in.MaxDrainTime
}

func (in *CheckpointPolicy) DeepCopy() *CheckpointPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *CheckpointReference) DeepCopyInto(out *CheckpointReference) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

func (in *CheckpointReference) DeepCopy() *CheckpointReference {
	if in == nil {
		return nil
	}
	out := new(CheckpointReference)
	in.DeepCopyInto(out)
	return out
}

func (in *ControlSpec) DeepCopyInto(out *ControlSpec) {
	*out = *in
}

func (in *ControlSpec) DeepCopy() *ControlSpec {
	if in == nil {
		return nil
	}
	out := new(ControlSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SuspensionStatus) DeepCopyInto(out *SuspensionStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

func (in *SuspensionStatus) DeepCopy() *SuspensionStatus {
	if in == nil {
		return nil
	}
	out := new(SuspensionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *EmbeddedObjectMetadata) DeepCopyInto(out *EmbeddedObjectMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *EmbeddedObjectMetadata) DeepCopy() *EmbeddedObjectMetadata {
	if in == nil {
		return nil
	}
	out := new(EmbeddedObjectMetadata)
	in.DeepCopyInto(out)
	return out
}

func (in *JobSetTemplate) DeepCopyInto(out *JobSetTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(EmbeddedObjectMetadata)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *JobSetTemplate) DeepCopy() *JobSetTemplate {
	if in == nil {
		return nil
	}
	out := new(JobSetTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumePolicy) DeepCopyInto(out *ResumePolicy) {
	*out = *in
}

func (in *ResumePolicy) DeepCopy() *ResumePolicy {
	if in == nil {
		return nil
	}
	out := new(ResumePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *ParallelismSpec) DeepCopyInto(out *ParallelismSpec) {
	*out = *in
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int32)
		**out = **in
	}
}

func (in *ParallelismSpec) DeepCopy() *ParallelismSpec {
	if in == nil {
		return nil
	}
	out := new(ParallelismSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AdmissionStatus) DeepCopyInto(out *AdmissionStatus) {
	*out = *in
	if in.AdmittedFlavors != nil {
		in, out := &in.AdmittedFlavors, &out.AdmittedFlavors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *AdmissionStatus) DeepCopy() *AdmissionStatus {
	if in == nil {
		return nil
	}
	out := new(AdmissionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
}

func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJob) DeepCopyInto(out *ResumableTrainingJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ResumableTrainingJob) DeepCopy() *ResumableTrainingJob {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJob)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ResumableTrainingJobIdentity) DeepCopyInto(out *ResumableTrainingJobIdentity) {
	*out = *in
}

func (in *ResumableTrainingJobIdentity) DeepCopy() *ResumableTrainingJobIdentity {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobIdentity)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJobList) DeepCopyInto(out *ResumableTrainingJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResumableTrainingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ResumableTrainingJobList) DeepCopy() *ResumableTrainingJobList {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ResumableTrainingJobRuntime) DeepCopyInto(out *ResumableTrainingJobRuntime) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *ResumableTrainingJobRuntime) DeepCopy() *ResumableTrainingJobRuntime {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobRuntime)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJobSpec) DeepCopyInto(out *ResumableTrainingJobSpec) {
	*out = *in
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	in.Identity.DeepCopyInto(&out.Identity)
	in.Runtime.DeepCopyInto(&out.Runtime)
	in.Checkpoint.DeepCopyInto(&out.Checkpoint)
	in.Resume.DeepCopyInto(&out.Resume)
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(ParallelismSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(ControlSpec)
		**out = **in
	}
}

func (in *ResumableTrainingJobSpec) DeepCopy() *ResumableTrainingJobSpec {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResumableTrainingJobStatus) DeepCopyInto(out *ResumableTrainingJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectedCheckpoint != nil {
		in, out := &in.SelectedCheckpoint, &out.SelectedCheckpoint
		*out = new(CheckpointReference)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadReference != nil {
		in, out := &in.WorkloadReference, &out.WorkloadReference
		*out = new(WorkloadReference)
		**out = **in
	}
	if in.CurrentSuspension != nil {
		in, out := &in.CurrentSuspension, &out.CurrentSuspension
		*out = new(SuspensionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCompletedCheckpoint != nil {
		in, out := &in.LastCompletedCheckpoint, &out.LastCompletedCheckpoint
		*out = new(CheckpointReference)
		(*in).DeepCopyInto(*out)
	}
	in.TransitionTimestamps.DeepCopyInto(&out.TransitionTimestamps)
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(AdmissionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreStatus)
		**out = **in
	}
}

func (in *ResumableTrainingJobStatus) DeepCopy() *ResumableTrainingJobStatus {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TransitionTimestamps) DeepCopyInto(out *TransitionTimestamps) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.StartingAt != nil {
		in, out := &in.StartingAt, &out.StartingAt
		*out = (*in).DeepCopy()
	}
	if in.RunningAt != nil {
		in, out := &in.RunningAt, &out.RunningAt
		*out = (*in).DeepCopy()
	}
	if in.YieldRequestedAt != nil {
		in, out := &in.YieldRequestedAt, &out.YieldRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.DrainingAt != nil {
		in, out := &in.DrainingAt, &out.DrainingAt
		*out = (*in).DeepCopy()
	}
	if in.LastCheckpointCompletedAt != nil {
		in, out := &in.LastCheckpointCompletedAt, &out.LastCheckpointCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.PausedAt != nil {
		in, out := &in.PausedAt, &out.PausedAt
		*out = (*in).DeepCopy()
	}
	if in.RestoringAt != nil {
		in, out := &in.RestoringAt, &out.RestoringAt
		*out = (*in).DeepCopy()
	}
	if in.RestoreCompletedAt != nil {
		in, out := &in.RestoreCompletedAt, &out.RestoreCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.SucceededAt != nil {
		in, out := &in.SucceededAt, &out.SucceededAt
		*out = (*in).DeepCopy()
	}
	if in.FailedAt != nil {
		in, out := &in.FailedAt, &out.FailedAt
		*out = (*in).DeepCopy()
	}
}

func (in *TransitionTimestamps) DeepCopy() *TransitionTimestamps {
	if in == nil {
		return nil
	}
	out := new(TransitionTimestamps)
	in.DeepCopyInto(out)
	return out
}

func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
