apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtj-operator.webhookServiceName" . }}
  namespace: {{ include "rtj-operator.namespace" . }}
  labels:
    {{- include "rtj-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rtj-operator.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: webhook-server
      protocol: TCP
      name: https
