//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionStatus) DeepCopyInto(out *AdmissionStatus) {
	*out = *in
	if in.AdmittedFlavors != nil {
		in, out := &in.AdmittedFlavors, &out.AdmittedFlavors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionStatus.
func (in *AdmissionStatus) DeepCopy() *AdmissionStatus {
	if in == nil {
		return nil
	}
	out := new(AdmissionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityStatus) DeepCopyInto(out *CapacityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityStatus.
func (in *CapacityStatus) DeepCopy() *CapacityStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPolicy) DeepCopyInto(out *CheckpointPolicy) {
	*out = *in
	out.Interval = in.Interval
	out.FreshnessBudget = in.FreshnessBudget
	out.MaxDrainTime = in.MaxDrainTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPolicy.
func (in *CheckpointPolicy) DeepCopy() *CheckpointPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPriorityPolicy) DeepCopyInto(out *CheckpointPriorityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPriorityPolicy.
func (in *CheckpointPriorityPolicy) DeepCopy() *CheckpointPriorityPolicy {
	if in == nil {
		return nil
	}
	out := new(CheckpointPriorityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointPriorityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPriorityPolicyList) DeepCopyInto(out *CheckpointPriorityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CheckpointPriorityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPriorityPolicyList.
func (in *CheckpointPriorityPolicyList) DeepCopy() *CheckpointPriorityPolicyList {
	if in == nil {
		return nil
	}
	out := new(CheckpointPriorityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointPriorityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPriorityPolicySpec) DeepCopyInto(out *CheckpointPriorityPolicySpec) {
	*out = *in
	out.CheckpointFreshnessTarget = in.CheckpointFreshnessTarget
	out.StartupProtectionWindow = in.StartupProtectionWindow
	out.MinRuntimeBetweenYields = in.MinRuntimeBetweenYields
	if in.YieldWindow != nil {
		in, out := &in.YieldWindow, &out.YieldWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.FailOpenOnTelemetryLoss != nil {
		in, out := &in.FailOpenOnTelemetryLoss, &out.FailOpenOnTelemetryLoss
		*out = new(bool)
		**out = **in
	}
	if in.FailOpenOnCheckpointStoreErrors != nil {
		in, out := &in.FailOpenOnCheckpointStoreErrors, &out.FailOpenOnCheckpointStoreErrors
		*out = new(bool)
		**out = **in
	}
	if in.ProtectedBoost != nil {
		in, out := &in.ProtectedBoost, &out.ProtectedBoost
		*out = new(int32)
		**out = **in
	}
	if in.CooldownBoost != nil {
		in, out := &in.CooldownBoost, &out.CooldownBoost
		*out = new(int32)
		**out = **in
	}
	if in.StaleCheckpointBoost != nil {
		in, out := &in.StaleCheckpointBoost, &out.StaleCheckpointBoost
		*out = new(int32)
		**out = **in
	}
	if in.PreemptibleOffset != nil {
		in, out := &in.PreemptibleOffset, &out.PreemptibleOffset
		*out = new(int32)
		**out = **in
	}
	if in.MinEffectivePriority != nil {
		in, out := &in.MinEffectivePriority, &out.MinEffectivePriority
		*out = new(int32)
		**out = **in
	}
	if in.MaxEffectivePriority != nil {
		in, out := &in.MaxEffectivePriority, &out.MaxEffectivePriority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPriorityPolicySpec.
func (in *CheckpointPriorityPolicySpec) DeepCopy() *CheckpointPriorityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointPriorityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointPriorityPolicyStatus) DeepCopyInto(out *CheckpointPriorityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointPriorityPolicyStatus.
func (in *CheckpointPriorityPolicyStatus) DeepCopy() *CheckpointPriorityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointPriorityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointReference) DeepCopyInto(out *CheckpointReference) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointReference.
func (in *CheckpointReference) DeepCopy() *CheckpointReference {
	if in == nil {
		return nil
	}
	out := new(CheckpointReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlSpec) DeepCopyInto(out *ControlSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlSpec.
func (in *ControlSpec) DeepCopy() *ControlSpec {
	if in == nil {
		return nil
	}
	out := new(ControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceClaimSpec) DeepCopyInto(out *DeviceClaimSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Request.DeepCopyInto(&out.Request)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceClaimSpec.
func (in *DeviceClaimSpec) DeepCopy() *DeviceClaimSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRequestSpec) DeepCopyInto(out *DeviceRequestSpec) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRequestSpec.
func (in *DeviceRequestSpec) DeepCopy() *DeviceRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]DeviceClaimSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.RequestedDeviceClasses != nil {
		in, out := &in.RequestedDeviceClasses, &out.RequestedDeviceClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceClaimTemplateRefs != nil {
		in, out := &in.ResourceClaimTemplateRefs, &out.ResourceClaimTemplateRefs
		*out = make([]ResourceClaimTemplateReference, len(*in))
		copy(*out, *in)
	}
	if in.LastClaimFailureTime != nil {
		in, out := &in.LastClaimFailureTime, &out.LastClaimFailureTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveLaunchShape) DeepCopyInto(out *EffectiveLaunchShape) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveLaunchShape.
func (in *EffectiveLaunchShape) DeepCopy() *EffectiveLaunchShape {
	if in == nil {
		return nil
	}
	out := new(EffectiveLaunchShape)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticitySpec) DeepCopyInto(out *ElasticitySpec) {
	*out = *in
	if in.TargetWorkerCount != nil {
		in, out := &in.TargetWorkerCount, &out.TargetWorkerCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticitySpec.
func (in *ElasticitySpec) DeepCopy() *ElasticitySpec {
	if in == nil {
		return nil
	}
	out := new(ElasticitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticityStatus) DeepCopyInto(out *ElasticityStatus) {
	*out = *in
	if in.LastResizeCheckpoint != nil {
		in, out := &in.LastResizeCheckpoint, &out.LastResizeCheckpoint
		*out = new(CheckpointReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LastElasticTransitionTime != nil {
		in, out := &in.LastElasticTransitionTime, &out.LastElasticTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.LastResizeCompletedTime != nil {
		in, out := &in.LastResizeCompletedTime, &out.LastResizeCompletedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticityStatus.
func (in *ElasticityStatus) DeepCopy() *ElasticityStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedObjectMetadata) DeepCopyInto(out *EmbeddedObjectMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedObjectMetadata.
func (in *EmbeddedObjectMetadata) DeepCopy() *EmbeddedObjectMetadata {
	if in == nil {
		return nil
	}
	out := new(EmbeddedObjectMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSetTemplate) DeepCopyInto(out *JobSetTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(EmbeddedObjectMetadata)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSetTemplate.
func (in *JobSetTemplate) DeepCopy() *JobSetTemplate {
	if in == nil {
		return nil
	}
	out := new(JobSetTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchGateStatus) DeepCopyInto(out *LaunchGateStatus) {
	*out = *in
	if in.AdmissionCheckSummary != nil {
		in, out := &in.AdmissionCheckSummary, &out.AdmissionCheckSummary
		*out = make(map[string]AdmissionCheckState, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchGateStatus.
func (in *LaunchGateStatus) DeepCopy() *LaunchGateStatus {
	if in == nil {
		return nil
	}
	out := new(LaunchGateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchReadinessStatus) DeepCopyInto(out *LaunchReadinessStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchReadinessStatus.
func (in *LaunchReadinessStatus) DeepCopy() *LaunchReadinessStatus {
	if in == nil {
		return nil
	}
	out := new(LaunchReadinessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterStatus) DeepCopyInto(out *MultiClusterStatus) {
	*out = *in
	if in.NominatedClusters != nil {
		in, out := &in.NominatedClusters, &out.NominatedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoteObjectRef != nil {
		in, out := &in.RemoteObjectRef, &out.RemoteObjectRef
		*out = new(RemoteObjectReference)
		**out = **in
	}
	if in.RemoteCheckpoint != nil {
		in, out := &in.RemoteCheckpoint, &out.RemoteCheckpoint
		*out = new(RemoteCheckpointSummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterStatus.
func (in *MultiClusterStatus) DeepCopy() *MultiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MultiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParallelismSpec) DeepCopyInto(out *ParallelismSpec) {
	*out = *in
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParallelismSpec.
func (in *ParallelismSpec) DeepCopy() *ParallelismSpec {
	if in == nil {
		return nil
	}
	out := new(ParallelismSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityPolicyReference) DeepCopyInto(out *PriorityPolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityPolicyReference.
func (in *PriorityPolicyReference) DeepCopy() *PriorityPolicyReference {
	if in == nil {
		return nil
	}
	out := new(PriorityPolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityShapingStatus) DeepCopyInto(out *PriorityShapingStatus) {
	*out = *in
	if in.ProtectedUntil != nil {
		in, out := &in.ProtectedUntil, &out.ProtectedUntil
		*out = (*in).DeepCopy()
	}
	if in.LastCompletedCheckpointTime != nil {
		in, out := &in.LastCompletedCheckpointTime, &out.LastCompletedCheckpointTime
		*out = (*in).DeepCopy()
	}
	if in.LastYieldTime != nil {
		in, out := &in.LastYieldTime, &out.LastYieldTime
		*out = (*in).DeepCopy()
	}
	if in.LastResumeTime != nil {
		in, out := &in.LastResumeTime, &out.LastResumeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityShapingStatus.
func (in *PriorityShapingStatus) DeepCopy() *PriorityShapingStatus {
	if in == nil {
		return nil
	}
	out := new(PriorityShapingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningRequestReference) DeepCopyInto(out *ProvisioningRequestReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningRequestReference.
func (in *ProvisioningRequestReference) DeepCopy() *ProvisioningRequestReference {
	if in == nil {
		return nil
	}
	out := new(ProvisioningRequestReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatus) DeepCopyInto(out *ProvisioningStatus) {
	*out = *in
	if in.ProvisioningRequestRef != nil {
		in, out := &in.ProvisioningRequestRef, &out.ProvisioningRequestRef
		*out = new(ProvisioningRequestReference)
		**out = **in
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatus.
func (in *ProvisioningStatus) DeepCopy() *ProvisioningStatus {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCheckpointSummary) DeepCopyInto(out *RemoteCheckpointSummary) {
	*out = *in
	if in.LastCompletedCheckpointTime != nil {
		in, out := &in.LastCompletedCheckpointTime, &out.LastCompletedCheckpointTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCheckpointSummary.
func (in *RemoteCheckpointSummary) DeepCopy() *RemoteCheckpointSummary {
	if in == nil {
		return nil
	}
	out := new(RemoteCheckpointSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteObjectReference) DeepCopyInto(out *RemoteObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteObjectReference.
func (in *RemoteObjectReference) DeepCopy() *RemoteObjectReference {
	if in == nil {
		return nil
	}
	out := new(RemoteObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceClaimTemplateReference) DeepCopyInto(out *ResourceClaimTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceClaimTemplateReference.
func (in *ResourceClaimTemplateReference) DeepCopy() *ResourceClaimTemplateReference {
	if in == nil {
		return nil
	}
	out := new(ResourceClaimTemplateReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJob) DeepCopyInto(out *ResumableTrainingJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJob.
func (in *ResumableTrainingJob) DeepCopy() *ResumableTrainingJob {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResumableTrainingJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJobIdentity) DeepCopyInto(out *ResumableTrainingJobIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJobIdentity.
func (in *ResumableTrainingJobIdentity) DeepCopy() *ResumableTrainingJobIdentity {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJobList) DeepCopyInto(out *ResumableTrainingJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResumableTrainingJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJobList.
func (in *ResumableTrainingJobList) DeepCopy() *ResumableTrainingJobList {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResumableTrainingJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJobRuntime) DeepCopyInto(out *ResumableTrainingJobRuntime) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJobRuntime.
func (in *ResumableTrainingJobRuntime) DeepCopy() *ResumableTrainingJobRuntime {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJobSpec) DeepCopyInto(out *ResumableTrainingJobSpec) {
	*out = *in
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	out.Identity = in.Identity
	in.Runtime.DeepCopyInto(&out.Runtime)
	out.Checkpoint = in.Checkpoint
	out.Resume = in.Resume
	if in.Parallelism != nil {
		in, out := &in.Parallelism, &out.Parallelism
		*out = new(ParallelismSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologySpec)
		**out = **in
	}
	if in.PriorityPolicyRef != nil {
		in, out := &in.PriorityPolicyRef, &out.PriorityPolicyRef
		*out = new(PriorityPolicyReference)
		**out = **in
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = new(DeviceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Elasticity != nil {
		in, out := &in.Elasticity, &out.Elasticity
		*out = new(ElasticitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Control != nil {
		in, out := &in.Control, &out.Control
		*out = new(ControlSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJobSpec.
func (in *ResumableTrainingJobSpec) DeepCopy() *ResumableTrainingJobSpec {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumableTrainingJobStatus) DeepCopyInto(out *ResumableTrainingJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkloadReference != nil {
		in, out := &in.WorkloadReference, &out.WorkloadReference
		*out = new(WorkloadReference)
		**out = **in
	}
	if in.CurrentSuspension != nil {
		in, out := &in.CurrentSuspension, &out.CurrentSuspension
		*out = new(SuspensionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedCheckpoint != nil {
		in, out := &in.SelectedCheckpoint, &out.SelectedCheckpoint
		*out = new(CheckpointReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LastCompletedCheckpoint != nil {
		in, out := &in.LastCompletedCheckpoint, &out.LastCompletedCheckpoint
		*out = new(CheckpointReference)
		(*in).DeepCopyInto(*out)
	}
	in.TransitionTimestamps.DeepCopyInto(&out.TransitionTimestamps)
	if in.Admission != nil {
		in, out := &in.Admission, &out.Admission
		*out = new(AdmissionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreStatus)
		**out = **in
	}
	if in.LaunchReadiness != nil {
		in, out := &in.LaunchReadiness, &out.LaunchReadiness
		*out = new(LaunchReadinessStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.EffectiveLaunchShape != nil {
		in, out := &in.EffectiveLaunchShape, &out.EffectiveLaunchShape
		*out = new(EffectiveLaunchShape)
		**out = **in
	}
	if in.PriorityShaping != nil {
		in, out := &in.PriorityShaping, &out.PriorityShaping
		*out = new(PriorityShapingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LaunchGate != nil {
		in, out := &in.LaunchGate, &out.LaunchGate
		*out = new(LaunchGateStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Provisioning != nil {
		in, out := &in.Provisioning, &out.Provisioning
		*out = new(ProvisioningStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupRecovery != nil {
		in, out := &in.StartupRecovery, &out.StartupRecovery
		*out = new(StartupRecoveryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacityStatus)
		**out = **in
	}
	if in.MultiCluster != nil {
		in, out := &in.MultiCluster, &out.MultiCluster
		*out = new(MultiClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = new(DeviceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Elasticity != nil {
		in, out := &in.Elasticity, &out.Elasticity
		*out = new(ElasticityStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumableTrainingJobStatus.
func (in *ResumableTrainingJobStatus) DeepCopy() *ResumableTrainingJobStatus {
	if in == nil {
		return nil
	}
	out := new(ResumableTrainingJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumePolicy) DeepCopyInto(out *ResumePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumePolicy.
func (in *ResumePolicy) DeepCopy() *ResumePolicy {
	if in == nil {
		return nil
	}
	out := new(ResumePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeReadinessPolicy) DeepCopyInto(out *ResumeReadinessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeReadinessPolicy.
func (in *ResumeReadinessPolicy) DeepCopy() *ResumeReadinessPolicy {
	if in == nil {
		return nil
	}
	out := new(ResumeReadinessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResumeReadinessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeReadinessPolicyList) DeepCopyInto(out *ResumeReadinessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResumeReadinessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeReadinessPolicyList.
func (in *ResumeReadinessPolicyList) DeepCopy() *ResumeReadinessPolicyList {
	if in == nil {
		return nil
	}
	out := new(ResumeReadinessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResumeReadinessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeReadinessPolicySpec) DeepCopyInto(out *ResumeReadinessPolicySpec) {
	*out = *in
	if in.RequireCompleteCheckpoint != nil {
		in, out := &in.RequireCompleteCheckpoint, &out.RequireCompleteCheckpoint
		*out = new(bool)
		**out = **in
	}
	if in.MaxCheckpointAge != nil {
		in, out := &in.MaxCheckpointAge, &out.MaxCheckpointAge
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowInitialLaunchWithoutCheckpoint != nil {
		in, out := &in.AllowInitialLaunchWithoutCheckpoint, &out.AllowInitialLaunchWithoutCheckpoint
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeReadinessPolicySpec.
func (in *ResumeReadinessPolicySpec) DeepCopy() *ResumeReadinessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ResumeReadinessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResumeReadinessPolicyStatus) DeepCopyInto(out *ResumeReadinessPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResumeReadinessPolicyStatus.
func (in *ResumeReadinessPolicyStatus) DeepCopy() *ResumeReadinessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ResumeReadinessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupRecoveryStatus) DeepCopyInto(out *StartupRecoveryStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupRecoveryStatus.
func (in *StartupRecoveryStatus) DeepCopy() *StartupRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(StartupRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuspensionStatus) DeepCopyInto(out *SuspensionStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuspensionStatus.
func (in *SuspensionStatus) DeepCopy() *SuspensionStatus {
	if in == nil {
		return nil
	}
	out := new(SuspensionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyDomainStatus) DeepCopyInto(out *TopologyDomainStatus) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyDomainStatus.
func (in *TopologyDomainStatus) DeepCopy() *TopologyDomainStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologySpec) DeepCopyInto(out *TopologySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologySpec.
func (in *TopologySpec) DeepCopy() *TopologySpec {
	if in == nil {
		return nil
	}
	out := new(TopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyStatus) DeepCopyInto(out *TopologyStatus) {
	*out = *in
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]TopologyDomainStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyStatus.
func (in *TopologyStatus) DeepCopy() *TopologyStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionTimestamps) DeepCopyInto(out *TransitionTimestamps) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.QueuedAt != nil {
		in, out := &in.QueuedAt, &out.QueuedAt
		*out = (*in).DeepCopy()
	}
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.StartingAt != nil {
		in, out := &in.StartingAt, &out.StartingAt
		*out = (*in).DeepCopy()
	}
	if in.RunningAt != nil {
		in, out := &in.RunningAt, &out.RunningAt
		*out = (*in).DeepCopy()
	}
	if in.YieldRequestedAt != nil {
		in, out := &in.YieldRequestedAt, &out.YieldRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.DrainingAt != nil {
		in, out := &in.DrainingAt, &out.DrainingAt
		*out = (*in).DeepCopy()
	}
	if in.LastCheckpointCompletedAt != nil {
		in, out := &in.LastCheckpointCompletedAt, &out.LastCheckpointCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.PausedAt != nil {
		in, out := &in.PausedAt, &out.PausedAt
		*out = (*in).DeepCopy()
	}
	if in.RestoringAt != nil {
		in, out := &in.RestoringAt, &out.RestoringAt
		*out = (*in).DeepCopy()
	}
	if in.RestoreCompletedAt != nil {
		in, out := &in.RestoreCompletedAt, &out.RestoreCompletedAt
		*out = (*in).DeepCopy()
	}
	if in.SucceededAt != nil {
		in, out := &in.SucceededAt, &out.SucceededAt
		*out = (*in).DeepCopy()
	}
	if in.FailedAt != nil {
		in, out := &in.FailedAt, &out.FailedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionTimestamps.
func (in *TransitionTimestamps) DeepCopy() *TransitionTimestamps {
	if in == nil {
		return nil
	}
	out := new(TransitionTimestamps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
